import toSquaresObj from './toSquaresObj';

const SQUARES = [
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  'W',
  'B',
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  'B',
  'W',
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
];

describe('toSquaresObj suite', () => {
  it('#toSquaresObj default ', () => {
    const pieces = toSquaresObj(SQUARES);
		expect( pieces ).toEqual( { '27': 'W', '28': 'B', '35': 'B', '36': 'W' } );
  });
});
